Section "InputClass"
    Identifier "Apple Magic Trackpad"
    MatchProduct "Apple Inc. Magic Trackpad"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "on"
    Option "TappingDrag" "on"
    Option "TappingDragLock" "on"
    Option "NaturalScrolling" "false"
    Option "AccelSpeed" "0.8"
EndSection
